### PR TITLE
Pagination Bugs

### LINKED ISSUE #70: Fix Pagination Bug
## Expected Behavior
When you go to page 6, there should be displayed results.

## Actual/Current Behavior
Once you go to page 6, the app breaks. Could be either the pagination functionality issue, or a limitation of the API.

### LINKED ISSUE #72: Handle Pagination Server Response
## Expected Behavior
The app should display a user friendly error message when the server API call is invoked when pagination.

## Actual/Current Behavior
The app breaks since there are no handlers when the server returns an error.

### LINKED ISSUE #76: Pagination Hover Cursor
## Expected Behavior
When the user hovers over the pagination buttons, there should be a cursor pointer.

## Actual/Current Behavior
There are no cursor pointers on hovering the pagination buttons.

### LINKED ISSUE #78: Pagination Margin Bottom
## Expected Behavior
There should be some margin-bottom at the pagination for a clean separation of the bottom screen.

## Actual/Current Behavior
There is no margin-bottom at the pagination.

### LINKED ISSUE #80: Change Pagination onClick Location
## Expected Behavior
The `onClick` function should be in the `div` element for "down-btn".

## Actual/Current Behavior
The `onClick` function is in the `img` element from the "down-btn" `div` parent elemtent.

### LINKED ISSUE #81: Pagination Dark Theme
## Expected Behavior
There should be a dark theme for the pagination.

## Actual/Current Behavior
There is no dark theme being activated for the pagination.

### LINKED ISSUE #82: Reset Pagination State
## Expected Behavior
When the user enters a new search field, the state of the pagination holding the page number should reset to number 1.

## Actual/Current Behavior
The page number is not being reset after entering a new search field.

### PR DESCRIPTION
**Pull request by BlackCubes**
## Changes
1. Fixed the `totalResults` for the pagination so that it would not call the News API with greater than 5 pages.
2. Handled the pagination server response with the `Snackbar` component so any errors would not break the end, and display a friendly message.
3. Added a cursor when hovering the pagination buttons.
4. Added `margin-bottom` to the pagination container so there could be space from the bottom.
5. Changed the location of the `onClick` function for "down-btn" to be on the `div` parent element and not its `img` child element.
6. Added a Dark Theme to the pagination buttons.
7. Reset the pagination state back to 1 if the user enters a new search field.

## Purpose
The purpose of this PR is to fix a few bugs on the pagination such as the limit of calling the `page` query parameter for the News API, handling the server responses when paginating, there were no cursors for the pagination buttons, the location of the `onClick` should not be in the `img` element, there were no Dark Theme on the pagination buttons, and the pagination state was not being reset back to 1 when a user enters a new search field.

## Approach
As described in the **Purpose** section above, all of these issues became resolved.

Closes #70 
Closes #72 
Closes #76 
Closes #78 
Closes #80 
Closes #81 
Closes #82

### CODE REVIEW

File: the-toad-tribune/src/layout/SearchResults.tsx [hunk 1]
```diff
@@ -47,22 +56,44 @@ const SearchResults: React.FC<SearchResultsProps> = ({
...
+
+    getNewsEverything(searchStuff).then((results) => {
+      if (results.status === "ok") {
+        setSearchResults(results);
+      }
+
+      if (results.status === "error") {
+        setSnackbarMessage(results.message);
+      }
+    });
```
Comment (gonzalespaulb) [inline the-toad-tribune/src/layout/SearchResults.tsx:74]: Props for taking care of error states

**Review by connielion — APPROVED** [review]
Looks great! Can’t wait to read in dark mode!

**Review by gonzalespaulb — APPROVED** [review]
